namespace CodeLearn
{
    internal class Program
    {
        static void Main(string[] args)
        {
            /*
            Ex1.RunCode();
            Console.WriteLine("-----------------------");
            Ex2.RunCode();
            Console.WriteLine("-----------------------");
            Ex3.RunCode();
            Console.WriteLine("-----------------------");
            Ex4.RunCode();
            Console.WriteLine("-----------------------");
            Ex5.RunCode();
            Console.WriteLine("-----------------------");
            //This is a comment
            Ex7.RunCode();
            Console.WriteLine("-----------------------");
            Ex8.RunCode();
            Console.WriteLine("-----------------------");
            Ex9.RunCode();
            Console.WriteLine("-----------------------");
            Ex10.RunCode();
            Console.WriteLine("-----------------------");
            Ex11.RunCode();
            Console.WriteLine("-----------------------");
            Ex12.RunCode();
            Console.WriteLine("-----------------------");
            Ex13.RunCode();
            Console.WriteLine("-----------------------");
            Ex14.RunCode();
            Console.WriteLine("-----------------------");
            Ex15.RunCode();
            Console.WriteLine("-----------------------");   
            Ex16.RunCode();
            Console.WriteLine("-----------------------");
            Ex17.RunCode();
            Console.WriteLine("-----------------------");
            Ex18.RunCode();
            Console.WriteLine("-----------------------");
            Ex19.RunCode();
            Console.WriteLine("-----------------------");
            Ex21.RunCode();
            Console.WriteLine("-----------------------");
            Ex22.RunCode();
            Console.WriteLine("-----------------------");
            Ex23.RunCode();
            Console.WriteLine("-----------------------"); 
            Ex24.RunCode();
            Console.WriteLine("-----------------------");
            Ex25.RunCode();
            Console.WriteLine("-----------------------");
            Ex26.RunCode();
            Console.WriteLine("-----------------------");
            Ex27.RunCode();
            Console.WriteLine("-----------------------");
            Ex28.RunCode();
            Console.WriteLine("-----------------------");
            Ex29.RunCode();
            Console.WriteLine("-----------------------");
            Ex30.RunCode();
            Console.WriteLine("-----------------------");
            Ex31.RunCode();
            Console.WriteLine("-----------------------");
            Ex32.RunCode();
            Console.WriteLine("-----------------------");
            Ex33.RunCode();
            Console.WriteLine("-----------------------");
            Ex34.RunCode();
            Console.WriteLine("-----------------------");
            Ex35.RunCode();
            Console.WriteLine("-----------------------"); 
            Ex36.RunCode();
            Console.WriteLine("-----------------------");
            Ex38.RunCode();
            Console.WriteLine("-----------------------");
            Ex41.RunCode();
            Console.WriteLine("\n-----------------------");
            Ex43.RunCode();
            Console.WriteLine("\n-----------------------");
            Ex45.RunCode();
            Console.WriteLine("\n-----------------------");
            Ex46.RunCode();
            Console.WriteLine("\n-----------------------");
            Ex47.RunCode();
            Console.WriteLine("-----------------------");
            Ex49.RunCode();
            Console.WriteLine("\n-----------------------");*/
            Ex50.RunCode();
            Console.WriteLine("\n-----------------------");

        }

    }
}